# Generated by Django 4.1.5 on 2023-05-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_checkinanalytics_num_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinanalytics",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ballkid",
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="captainanalytics",
            unique_together={("ballkid", "captain")},
        ),
        migrations.AlterUniqueTogether(
            name="courtanalytics",
            unique_together={("ballkid", "court")},
        ),
        migrations.AlterUniqueTogether(
            name="cuthistory",
            unique_together={("ballkid", "year")},
        ),
        migrations.AlterUniqueTogether(
            name="finalshistory",
            unique_together={("ballkid", "year")},
        ),
    ]
