# Generated by Django 4.1.5 on 2023-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_checkinanalytics_ballkid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuthistory",
            name="is_cut",
        ),
        migrations.RemoveField(
            model_name="cuthistory",
            name="time",
        ),
        migrations.AddField(
            model_name="cuthistory",
            name="furthest_date",
            field=models.DateField(null=True),
        ),
    ]
