# Generated by Django 4.1.5 on 2023-05-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_cuthistory_is_cut_remove_cuthistory_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuthistory",
            name="num_years_experience",
        ),
        migrations.RemoveField(
            model_name="finalshistory",
            name="num_years_experience",
        ),
    ]
