# Generated by Django 4.1.5 on 2023-05-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_remove_cuthistory_num_years_experience_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cuthistory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cuthistory",
            name="is_cut",
            field=models.BooleanField(default=False),
        ),
    ]
