# Generated by Django 4.1.5 on 2023-05-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_cuthistory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationparams",
            name="ballkid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.ballkid",
                unique=True,
            ),
        ),
    ]
