# Generated by Django 4.1.5 on 2023-05-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_calibrationparams_ballkid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationparams",
            name="ballkid",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.ballkid"
            ),
        ),
    ]
