# Generated by Django 4.1.5 on 2023-05-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_calibrationparams_num_ratee_ratings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="num_raters",
            field=models.IntegerField(default=0),
        ),
    ]
