# Generated by Django 4.1.5 on 2023-05-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_calibrationparams_num_raters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationparams",
            name="num_ratee_ratings",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationparams",
            name="num_rater_ratings",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calibrationparams",
            name="num_raters",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
