# Generated by Django 4.1.5 on 2023-05-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_calibrationparams_num_ratee_ratings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationparams",
            name="num_ratee_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="calibrationparams",
            name="num_rater_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="calibrationparams",
            name="num_raters",
            field=models.IntegerField(default=0),
        ),
    ]
