# Generated by Django 4.1.5 on 2023-05-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_rename_num_days_checkinanalytics_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkinhistory",
            old_name="checkout",
            new_name="end",
        ),
        migrations.RenameField(
            model_name="checkinhistory",
            old_name="checkin",
            new_name="start",
        ),
    ]
