# Generated by Django 4.1.5 on 2023-06-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_rename_checkout_checkinhistory_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtanalytics",
            name="court",
            field=models.CharField(
                choices=[
                    ("Stadium", "Stadium"),
                    ("Court 4", "Four"),
                    ("Harris", "Harris"),
                    ("Court 5", "Five"),
                    ("Grandstand", "Grandstand"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="court",
            field=models.CharField(
                choices=[
                    ("Stadium", "Stadium"),
                    ("Court 4", "Four"),
                    ("Harris", "Harris"),
                    ("Court 5", "Five"),
                    ("Grandstand", "Grandstand"),
                ],
                max_length=10,
            ),
        ),
    ]
