# Generated by Django 4.1.5 on 2023-07-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_courtanalytics_court_alter_schedule_court"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_raw_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="ratee_raw_stdev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="rater_raw_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calibrationparams",
            name="rater_raw_stdev",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
