# Generated by Django 4.1.5 on 2023-07-24 12:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_ballkid_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="emergency_name",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="ballkid",
            name="emergency_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="ballkid",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
