# Generated by Django 4.1.5 on 2023-07-28 01:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_rename_banner_tournament_banner1_tournament_banner2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finalshistory",
            old_name="year",
            new_name="count",
        ),
        migrations.AlterUniqueTogether(
            name="finalshistory",
            unique_together={("ballkid", "match_type")},
        ),
        migrations.AddField(
            model_name="finalshistory",
            name="years",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
