# Generated by Django 4.1.5 on 2023-07-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_rename_year_finalshistory_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="checkout_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballkid",
            name="schedule_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
