# Generated by Django 4.1.5 on 2023-08-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_tournament_banner1_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="rcal_ignore_outliers",
            field=models.FloatField(default=1.5),
        ),
    ]
