# Generated by Django 4.1.5 on 2023-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_remove_ballkid_schedule_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinhistory",
            name="is_first_checkin",
            field=models.BooleanField(default=True),
        ),
    ]
