# Generated by Django 4.1.5 on 2024-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_banner_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="audience",
            field=models.CharField(default="all", max_length=20),
        ),
    ]
