# Generated by Django 4.1.5 on 2024-07-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_calibrationparams_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballkid",
            name="num_tickets_used",
            field=models.IntegerField(default=0),
        ),
    ]
