# Generated by Django 4.1.5 on 2024-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_ballkid_num_tickets_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballkid",
            name="checkout_comments",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1pm", "One"),
                    ("2pm", "Two"),
                    ("3pm", "Three"),
                    ("4pm", "Four"),
                    ("5pm", "Five"),
                    ("6pm", "Six"),
                    ("7pm", "Seven"),
                    ("8pm", "Eight"),
                    ("9pm", "Nine"),
                    ("10pm", "Ten"),
                    ("11pm", "Eleven"),
                    ("12am", "Midnight"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
