# Generated by Django 4.1.5 on 2024-07-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_rating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="rcal_bucket_size",
            field=models.IntegerField(default=3),
        ),
    ]
